### ISSUE TITLE
support for 1.15.2?

### ISSUE THREAD

**Issue by DylanHDonsky** [UpcraftLP/Piston-Expansion#1]
could there be an update to support 1.15.2? it seems since this is only affecting the single piston block that it should be compatible but i am unsure as to how to go about installing it for 1.15.2 if it will even let me. i figure maybe there is an easy way to make it compatible?

**Comment by UpcraftLP** [comment]
No, the mod will not work on 1.15 due to the massive changes in both the Minecraft code as well as Forge having been completely rewritten for 1.13+

Porting this to 1.15 would mean a complete rewrite, and I don't have the time to do that.

However, feel free to fork the project and update it yourself, if you wish to.

**Comment by MaxiHuHe04** [comment]
Two years ago I made a mod using MCP that does essentially the same thing as this one for the YouTuber Phoenix SC. (This mod was inspirated by mine :D) As MCP got abandoned, I recreated it in Fabric a while ago for 1.14.4 and it still works just fine in 1.15.2. Maybe sometime later I will upload it to CurseForge, but for now it is on Dropbox. So if you are fine with Fabric instead of Forge too, you can download it here: https://bit.ly/pistonpushlimitmod
